# Generated by Django 5.0.3 on 2024-03-21 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmgmtapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksmgmtmodel',
            old_name='availability',
            new_name='availability_status',
        ),
        migrations.RemoveField(
            model_name='booksmgmtmodel',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksmgmtmodel',
            name='status',
        ),
        migrations.AddField(
            model_name='booksmgmtmodel',
            name='book_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
