# Generated by Django 5.0.3 on 2024-03-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmgmtapi', '0002_rename_availability_booksmgmtmodel_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmgmtmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='booksmgmtmodel',
            name='book_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
