# Generated by Django 5.0.3 on 2024-03-26 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmgmtapi', '0003_remove_booksmgmtmodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmgmtmodel',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booksmgmtmodel',
            name='availability_status',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
