# Generated by Django 5.0.3 on 2024-03-19 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowBookModel',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('borrowing_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
