# Generated by Django 5.0.3 on 2024-03-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookborrowapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowbookmodel',
            name='submitted_date',
            field=models.DateField(null=True),
        ),
    ]
