# Generated by Django 5.0.3 on 2024-03-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookborrowapi', '0002_borrowbookmodel_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbookmodel',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
